canonical: http://hl7.org/fhir/us/vrdr
title: "Vital Records Death Reporting (VRDR) FHIR Implementation Guide"
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
id: hl7.fhir.us.vrdr
name: VRDR
status: draft
version: 3.0.0-ballot
releaseLabel: ballot  # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
dependencies:
  hl7.fhir.us.core: 5.0.1
  hl7.fhir.us.odh: 1.2.0
  hl7.fhir.us.vr-common-library: 
    version: current 
    id: hl7fhirusvrcommonlibrary
  us.cdc.phinvads:
    uri: http://fhir.org/packages/us.cdc.phinvads/ImplementationGuide/us.cdc.phinvads
    version: 0.12.0 
pages:
  index.md:
    title: Home
  credits.md:
    title: Credits
  background.md:
    title: Background
  scope_of_the_vrdr_fhir_ig.md:
    title: Scope of the VRDR IG
  usage.md:
    title: Usage
  conformance.md:
    title: Conformance
  artifacts.html:
    title: Artifacts Summary
  vrdr_forms_mapping.md:
    title: VRDR Forms Mapping
  DeathRecordDataDictionary.md:
    title: Death Record Data Dictionary
  MortalityRosterDataDictionary.md:
    title: Mortality Roster Data Dictionary
  downloads.md:
    title: Download Specification
  change_log.md:
    title: Change Log
  content-transitions.md:
    title: Content Transitions 
menu:
  Home:
    Home: index.html
    Background: background.html
    Scope: scope_of_the_vrdr_fhir_ig.html
    Credits: credits.html
  Implementer Guidance:
    Usage Notes: usage.html
    Conformance: conformance.html
    Death Record Data Dictionary: DeathRecordDataDictionary.html
    Mortality Roster Data Dictionary: MortalityRosterDataDictionary.html
    IJE Mapping to FHIR (xlsx): IJE_File_Layouts_Version_2021_FHIR.xlsx
    Forms Mapping: vrdr_forms_mapping.html
  Artifacts: artifacts.html
  Changes:
    Change Log: change_log.html
    STU2.2 to STU3 Changes: content-transitions.html
  Downloads: downloads.html

groups:
  DecedentDemographics:
    name: Decedent Demographics
    description: Demographic data includes information about related persons (Mother, Father, and Spouse) and social determinants such as education level. The information in this profile group are provided by a decedent informant.
    resources:
    - Decedent
    - DecedentAge
    - DecedentEducationLevel
    - DecedentMother
    - DecedentFather
    - DecedentSpouse
    - DecedentMilitaryService
  RecordLinkages:
    name: Record Linkages
    description: Record Linkages enable deaths to be linked to associated vital records reports
    resources:
    - BirthRecordIdentifier
    - BirthRecordIdentifierChild
    - FetalDeathRecordIdentifier
  DeathInvestigation:
    name: Death Investigation
    description: Data obtained during the course of investigating a death. Many of these items are conditionally present in a death certification transaction depending on whether or not an autopsy was performed, an injury incident occurred, or a transportation event was involved. The details on the pronouncement performer can be provided using USCore Practitioner profile.
    resources:
    - AutopsyPerformedIndicator
    - DeathDate 
    - DecedentPregnancyStatus
    - DeathLocation
    - ExaminerContacted
    - InjuryLocation
    - InjuryIncident 
    - SurgeryDate
    - TobaccoUseContributedToDeath 
  DeathCertification:
    name: Death Certification
    description: Data related to the primary concern of the VRDR IG, Death Certification. In this group, the causes of death and the causal pathway are documented and attested to by a death certifier (coroner or medical examiner).
    resources:
    - Certifier
    - CauseOfDeathPart1
    - CauseOfDeathPart2
    - DeathCertification 
    - MannerOfDeath 
  DecedentDisposition:
    name: Decedent Disposition
    description: Data related to the disposition of the decedents remains. The data in this profile group is typically provided by the funeral home performing the disposition services. The content of this profile group is authenticated by the funeral home director. Additional content can be included using standard USCore profiles, and can be included to specify the Funeral Home Director, the Licensee, and the Mortician.
    resources:
    - DispositionLocation
    - DecedentDispositionMethod
    - FuneralHome
    - Mortician 
  CodedObservations:
    name: Coded Observations
    description: Coded Observations based on the submitted death record.
    resources:
    - ActivityAtTimeOfDeath
    - AutomatedUnderlyingCauseOfDeath
    - ManualUnderlyingCauseOfDeath
    - RecordAxisCauseOfDeath
    - EntityAxisCauseOfDeath
    - PlaceOfInjury
    # - StructureDefinition/vrdr-coded-race-and-ethnicity
    - CodingStatusValues
  DocumentsAndBundles:
    name: Documents and Bundles
    description: Documents and Bundles used to transmit death record content.
    resources:
    - CauseOfDeathCodedContentBundle
    - DemographicCodedContentBundle
    - DeathCertificate
    - DeathCertificateDocument 
    - MortalityRosterBundle
    - IndustryOccupationCodedContentBundle
  ExampleBundles:
    name: Example Bundles
    description: Example Death Certificate, Coded Content, and Mortality Roster Bundles
    resources:
    - DeathCertificateDocument-UT-1
    - DeathCertificateUT-Example1
    - DeathCertification-Example1
    - DeathCertification-Example2
    - CauseOfDeathCodedContentBundle-Example1
    - DemographicCodedContentBundle-Example1
    - MortalityRosterBundle-Example1
copyrightYear: 2022+
publisher:
  name: HL7 International / Public Health
  url: http://www.hl7.org/Special/committees/pher
  email: pher@lists.HL7.org
parameters:
  show-inherited-invariants: false
  jira-code: vrdr
  path-expansion-params: '../../exp-params.json'  #path is relative to [base]/fsh-generated/resources
  version-comparison-master: true 
  auto-oid-root: 2.16.840.1.113883.4.642.40.10

jurisdiction: urn:iso:std:iso:3166#US
license: CC0-1.0

extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: pher