canonical: http://hl7.org/fhir/us/vrdr
releaseLabel: STU 2 (Post-Ballot, Pre-Publication Draft)
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
id: hl7.fhir.us.vrdr
name: VRDR
status: draft
version: 1.2.0
dependencies:
  hl7.fhir.us.core: 3.1.0
  hl7.fhir.us.vr-common-library: 0.1.0
  hl7.fhir.us.odh: 1.0.0
  us.cdc.phinvads:
    uri: http://fhir.org/packages/us.cdc.phinvads
    version: 0.7.0
menu:
  Home: index.html
  Artifacts: artifacts.html
copyrightYear: 2021+
publisher:
  name: HL7 Public Health Working Group
  url: http://www.hl7.org/Special/committees/pher/index.cfm
  email: pher@lists.HL7.org
parameters:
  show-inherited-invariants: false
  jira-code: vrdr
jurisdiction: urn:iso:std:iso:3166#US
license: CC0-1.0
