Alias: $v2-0136 = http://terminology.hl7.org/CodeSystem/v2-0136
Alias: $v3-NullFlavor = http://terminology.hl7.org/CodeSystem/v3-NullFlavor
Alias: $v3-EducationLevel = http://terminology.hl7.org/CodeSystem/v3-EducationLevel
Alias: $v3-MaritalStatus = http://terminology.hl7.org/CodeSystem/v3-MaritalStatus
Alias: $vrdrMissingValueReason = http://hl7.org/fhir/us/vrdr/CodeSystem/vrdrMissingValueReason
Alias: $loinc = http://loinc.org
Alias: $sct = http://snomed.info/sct
Alias: $v2-0203 = http://terminology.hl7.org/CodeSystem/v2-0203
Alias: $documentSectionCodeSystem = http://hl7.org/fhir/us/vrdr/CodeSystem/documentSectionCodeSystem
Alias: $list-order = http://terminology.hl7.org/CodeSystem/list-order
Alias: $v3-RoleCode = http://terminology.hl7.org/CodeSystem/v3-RoleCode
Alias: $location-physical-type = http://terminology.hl7.org/CodeSystem/location-physical-type
Alias: $ViewCodeSystem.action = https://phinvads.cdc.gov/vads/ViewCodeSystem.action?id=2.16.840.1.114222.4.5.274
Alias: $organization-type = http://terminology.hl7.org/CodeSystem/organization-type
Alias: $bypassEditFlagCodeSystem = http://hl7.org/fhir/us/vrdr/CodeSystem/bypassEditFlagCodeSystem
Alias: $administrative-gender = http://hl7.org/fhir/administrative-gender
Alias: $Cause-Of-Death-Condition = http://hl7.org/fhir/us/vrdr/StructureDefinition/Cause-Of-Death-Condition
Alias: $patient-birthPlace = http://hl7.org/fhir/StructureDefinition/patient-birthPlace
Alias: $ViewValueSet.action = https://phinvads.cdc.gov/vads/ViewValueSet.action?id=282D4DD8-39EA-4C5B-B8A9-B2C3E5878A15#
Alias: $ViewValueSet.action_1 = https://phinvads.cdc.gov/vads/ViewValueSet.action?oid=2.16.840.1.114222.4.11.6001
Alias: $place-of-death = http://hl7.org/fhir/us/vrdr/ValueSet/place-of-death
Alias: $ViewValueSet.action_2 = https://phinvads.cdc.gov/vads/ViewValueSet.action?id=C2F2220B-270F-4BDF-9F8C-D5CB369F7212
// Alias: $edit-Bypass-01 = http://hl7.org/fhir/us/vrdr/ValueSet/edit-Bypass-01
Alias: $method-of-disposition = http://hl7.org/fhir/us/vrdr/ValueSet/method-of-disposition
Alias: $education-level = http://hl7.org/fhir/us/vrdr/ValueSet/education-level
// Alias: $edit-Bypass-01234 = http://hl7.org/fhir/us/vrdr/ValueSet/Edit-Bypass-01234
Alias: $ViewValueSet.action_3 = https://phinvads.cdc.gov/vads/ViewValueSet.action?oid=2.16.840.1.114222.4.11.6003
// Alias: $edit-Bypass-012 = http://hl7.org/fhir/us/vrdr/ValueSet/Edit-Bypass-012
Alias: $ViewValueSet.action_4 = https://phinvads.cdc.gov/vads/ViewValueSet.action?id=8B471CEB-EA88-45A4-8FAD-7805402A53F7
Alias: $administrative-gender_1 = http://hl7.org/fhir/us/vrdr/ValueSet/administrative-gender
Alias: $ViewValueSet.action_5 = https://phinvads.cdc.gov/vads/ViewValueSet.action?id=BF77DB9E-1023-4CBE-A79D-7354FF9C968C
Alias: $marital-status = http://hl7.org/fhir/us/vrdr/ValueSet/marital-status
// Alias: $edit-Bypass-0124 = http://hl7.org/fhir/us/vrdr/ValueSet/Edit-Bypass-0124
Alias: $ViewValueSet.action_6 = https://phinvads.cdc.gov/vads/ViewValueSet.action?oid=2.16.840.1.114222.4.11.8018
Alias: $v3-ServiceDeliveryLocationRoleType = http://terminology.hl7.org/ValueSet/v3-ServiceDeliveryLocationRoleType
Alias: $ViewValueSet.action_7 = https://phinvads.cdc.gov/vads/ViewValueSet.action?oid=2.16.840.1.114222.4.11.7374
Alias: $manner-of-death = http://hl7.org/fhir/us/vrdr/ValueSet/manner-of-death
Alias: $ViewValueSet.action_8 = https://phinvads.cdc.gov/vads/ViewValueSet.action?oid=2.16.840.1.114222.4.11.6004
Alias: $vrdrYesNoUnknown = http://hl7.org/fhir/us/vrdr/ValueSet/vrdr-YesNoUnknown
Alias: $raceMissingValueReason = http://hl7.org/fhir/us/vrdr/ValueSet/raceMissingValueReason
Alias: $v2-0532 = http://terminology.hl7.org/CodeSystem/v2-0532
Alias: $admingender = http://hl7.org/fhir/administrative-gender
Alias: $statesVS = http://hl7.org/fhir/us/core/ValueSet/us-core-usps-state
Alias: $statesCS = https://www.usps.com/
Alias: $provinces = http://canadapost.ca/CodeSystem/ProvinceCodes
Alias: $icd10PlaceOfOccurence = urn:oid:2.16.840.1.114222.4.5.320
Alias: $dataabsentreason401 = http://hl7.org/fhir/ValueSet/data-absent-reason|4.0.1
Alias: $Yes-No-Unknown = YesNoUnknownVS
Alias: $Yes-No-Unknown-NotApplicable = YesNoUnknownNotApplicableVS