// External CS and VS
Alias: $v2-0136 = http://terminology.hl7.org/CodeSystem/v2-0136
Alias: $v3-NullFlavor = http://terminology.hl7.org/CodeSystem/v3-NullFlavor
Alias: $v3-EducationLevel = http://terminology.hl7.org/CodeSystem/v3-EducationLevel
Alias: $v3-MaritalStatus = http://terminology.hl7.org/CodeSystem/v3-MaritalStatus
Alias: $loinc = http://loinc.org
Alias: $sct = http://snomed.info/sct
Alias: $v2-0203 = http://terminology.hl7.org/CodeSystem/v2-0203
Alias: $list-order = http://terminology.hl7.org/CodeSystem/list-order
Alias: $v3-RoleCode = http://terminology.hl7.org/CodeSystem/v3-RoleCode
Alias: $location-physical-type = http://terminology.hl7.org/CodeSystem/location-physical-type
Alias: $ViewCodeSystem.action = https://phinvads.cdc.gov/vads/ViewCodeSystem.action?id=2.16.840.1.114222.4.5.274
Alias: $organization-type = http://terminology.hl7.org/CodeSystem/organization-type
Alias: $administrative-gender = http://hl7.org/fhir/administrative-gender
Alias: $patient-birthPlace = http://hl7.org/fhir/StructureDefinition/patient-birthPlace
Alias: $v3-ServiceDeliveryLocationRoleType = http://terminology.hl7.org/ValueSet/v3-ServiceDeliveryLocationRoleType
Alias: $v2-0532 = http://terminology.hl7.org/CodeSystem/v2-0532
Alias: $admingender = http://hl7.org/fhir/administrative-gender
Alias: $statesVS = http://hl7.org/fhir/us/core/ValueSet/us-core-usps-state
Alias: $statesCS = https://www.usps.com/
Alias: $provinces = http://canadapost.ca/CodeSystem/ProvinceCodes
Alias: $icd10PlaceOfOccurence = urn:oid:2.16.840.1.114222.4.5.320
Alias: $dataabsentreason401 = http://hl7.org/fhir/ValueSet/data-absent-reason|4.0.1
// PHINVADS ValueSets --> most should be eliminated
Alias: $PHVSDivisionVitalStatisticsCounty = https://phinvads.cdc.gov/vads/ViewValueSet.action?id=C2F2220B-270F-4BDF-9F8C-D5CB369F7212
Alias: $PHVSDecedentBirthplaceCountry = https://phinvads.cdc.gov/vads/ViewValueSet.action?id=8B471CEB-EA88-45A4-8FAD-7805402A53F7
Alias: $PHVSDecedentResidentCountry = https://phinvads.cdc.gov/vads/ViewValueSet.action?id=BF77DB9E-1023-4CBE-A79D-7354FF9C968C
Alias: $PHVSCityPlacesNCHS = https://phinvads.cdc.gov/vads/ViewValueSet.action?id=D06EE94C-4D4C-440A-AD2A-1C3CB35E6D08#
Alias: $PH_Country_GEC = urn:oid:2.16.840.1.113883.13.250
// VRDR CS and VS
Alias: $Yes-No-Unknown = YesNoUnknownVS
Alias: $Yes-No-Unknown-NotApplicable = YesNoUnknownNotApplicableVS
Alias: $raceMissingValueReason = RaceMissingValueReasonVS
Alias: $place-of-death = PlaceOfDeathVS
Alias: $vrdrYesNoUnknown = YesNoUnknownVS
Alias: $manner-of-death = MannerOfDeathVS
Alias: $marital-status = MaritalStatusVS
Alias: $documentSectionCodeSystem = DocumentSectionCS
Alias: $education-level = EducationLevelVS
Alias: $bypassEditFlagCodeSystem = BypassEditFlagCS
Alias: $Cause-Of-Death-Condition = CauseOfDeathCondition
Alias: $method-of-disposition = MethodOfDispositionVS
Alias: $administrative-gender_1 = AdministrativeGenderVS