Extension: NVSSRace
Id: NVSS-Race
Title: "NVSS Race"
Description: "NVSS Race (Extension) that captures the RACE1-RACE23 flags and literals"
* insert Extension(White, 0, 1, White, White, boolean)
* insert Extension(BlackOrAfricanAmerican, 0, 1, Black Or African American, Black Or African American, boolean)
* insert Extension(AmericanIndianOrAlaskaNative, 0, 1, American Indian Or Alaska Native, American Indian Or Alaska Native, boolean)
* insert Extension(AsianIndian, 0, 1, Asian Indian, Asian Indian, boolean)
* insert Extension(Chinese, 0, 1, Chinese, CHinese, boolean)
* insert Extension(Filipino, 0, 1, Filipino, Filipino, boolean)
* insert Extension(Japanese, 0, 1, Japanese, Japanese, boolean)
* insert Extension(Korean, 0, 1, Korean, Korean, boolean)
* insert Extension(Vietnamese, 0, 1, Vietnamese,Vietnamese, boolean)
* insert Extension(OtherAsian, 0, 1, Other Asian, OtherAsian, boolean)
* insert Extension(NativeHawaiian, 0, 1, Native Hawaiian, Native Hawaiian, boolean)
* insert Extension(GuamanianOrChamorro, 0, 1, Guamanian Or Chamorro, Guamanian Or Chamorro, boolean)
* insert Extension(Samoan, 0, 1, Samoan, Samoan, boolean)
* insert Extension(OtherPacificIslander, 0, 1, Other Pacific Islander, Other Pacific Islander, boolean)
* insert Extension(OtherRace, 0, 1, Other Race, Other Race, boolean)
* insert Extension(AmericanIndianOrAlaskaNativeLiteral1, 0, 1, American Indian Or Alaska Native Literal 1, American Indian Or Alaska Native Literal 1, string)
* insert Extension(AmericanIndianOrAlaskaNativeLiteral2, 0, 1, American Indian Or Alaska Native Literal 2, American Indian Or Alaska Native Literal 2, string)
* insert Extension(OtherAsianLiteral1, 0, 1, Other Asian Literal 1, Other Asian Literal 1, string)
* insert Extension(OtherAsianLiteral2, 0, 1, Other Asian Literal 2, Other Asian Literal 2, string)
* insert Extension(OtherPacificIslanderLiteral1, 0, 1, Other Pacific Islander Literal 1, Other Pacific Islander Literal 1, string)
* insert Extension(OtherPacificIslanderLiteral2, 0, 1, Other Pacific Islander Literal 2, Other Pacific Islander Literal 2, string)
* insert Extension(OtherRaceLiteral1, 0, 1, Other Race Literal 1, Other Race Literal 1, string)
* insert Extension(OtherRaceLiteral2, 0, 1, Other Race Literal 2, Other Race Literal 2, string)
* insert Extension(MissingValueReason, 0, 1, Missing Value Reason, MissingValueReason, Coding)
* extension[MissingValueReason].value[x] from $raceMissingValueReason (required)
