Instance: RaceRecode40CM
InstanceOf: ConceptMap
// Id: vrdr-race-recode40-cm
Usage: #definition
* experimental = false
* insert ConceptMapIntro(RaceRecode40, RaceRecode40VS)
* insert AddGroup("MRE",[[Canonical(RaceRecode40CS)]])
* insert MapConcept(#01, "White", #01,  "White")
* insert MapConcept(#02, "Black", #02,  "Black")
* insert MapConcept(#03, "American Indian or Alaskan Native (AIAN\)", #03,  "American Indian or Alaskan Native (AIAN\)")
* insert MapConcept(#04, "Asian Indian", #04,  "Asian Indian")
* insert MapConcept(#05, "Chinese", #05,  "Chinese")
* insert MapConcept(#06, "Filipino", #06,  "Filipino")
* insert MapConcept(#07, "Japanese", #07,  "Japanese")
* insert MapConcept(#08, "Korean", #08,  "Korean")
* insert MapConcept(#09, "Vietnamese", #09,  "Vietnamese")
* insert MapConcept(#10, "Other or Multiple Asian", #10,  "Other or Multiple Asian")
* insert MapConcept(#11, "Hawaiian", #11,  "Hawaiian")
* insert MapConcept(#12, "Guamanian", #12,  "Guamanian")
* insert MapConcept(#13, "Samoan", #13,  "Samoan")
* insert MapConcept(#14, "Other or Multiple Pacific Islander", #14,  "Other or Multiple Pacific Islander")
* insert MapConcept(#15, "Black and White", #15,  "Black and White")
* insert MapConcept(#16, "Black and AIAN", #16,  "Black and AIAN")
* insert MapConcept(#17, "Black and Asian", #17,  "Black and Asian")
* insert MapConcept(#18, "AIAN and NHOPI", #18,  "AIAN and NHOPI")
* insert MapConcept(#19, "NHOPI and White", #19,  "NHOPI and White")
* insert MapConcept(#20, "AIAN and Asian", #20,  "AIAN and Asian")
* insert MapConcept(#21, "AIAN and NHOPI-2", #21,  "AIAN and NHOPI 2")
* insert MapConcept(#22, "Asian and White", #22,  "Asian and White")
* insert MapConcept(#23, "Asian and NHOPI", #23,  "Asian and NHOPI")
* insert MapConcept(#24, "NHOPI and White-2", #24,  "NHOPI and White 2")
* insert MapConcept(#25, "Black\, AIAN and White", #25,  "Black\, AIAN and White")
* insert MapConcept(#26, "Black\, AIAN and Asian", #26,  "Black\, AIAN and Asian")
* insert MapConcept(#27, "Black\, AIAN and NHOPI", #27,  "Black\, AIAN and NHOPI")
* insert MapConcept(#28, "Black\, Asian and White", #28,  "Black\, Asian and White")
* insert MapConcept(#29, "Black\, Asian and NHOPI", #29,  "Black\, Asian and NHOPI")
* insert MapConcept(#30, "Black\, NHOPI and White", #30,  "Black\, NHOPI and White")
* insert MapConcept(#31, "AIAN\, Asian and White", #31,  "AIAN\, Asian and White")
* insert MapConcept(#32, "AIAN\, NHOPI and White", #32,  "AIAN\, NHOPI and White")
* insert MapConcept(#33, "AIAN\, Asian and NHOPI", #33,  "AIAN\, Asian and NHOPI")
* insert MapConcept(#34, "Asian\, NHOPI and White", #34,  "Asian\, NHOPI and White")
* insert MapConcept(#35, "Black\, AIAN\, Asian and White", #35,  "Black\, AIAN\, Asian and White")
* insert MapConcept(#36, "Black\, AIAN\, Asian and NHOPI", #36,  "Black\, AIAN\, Asian and NHOPI")
* insert MapConcept(#37, "Black\, AIAN\, NHOPI and White", #37,  "Black\, AIAN\, NHOPI and White")
* insert MapConcept(#38, "Black\, Asian\, NHOPI and White", #38,  "Black\, Asian\, NHOPI and White")
* insert MapConcept(#39, "AIAN\, Asian\, NHOPI and White", #39,  "AIAN\, Asian\, NHOPI and White")
* insert MapConcept(#40, "Black\, AIAN\, Asian\, NHOPI and White", #40,  "Black\, AIAN\, Asian\, NHOPI and White")
* insert MapConcept(#99, "Unknown and Other Race", #99,  "Unknown and Other Race")
